global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "rpi-exporter"
    static_configs:
      - targets: ["rpi-exporter:9243"]

  - job_name: "sonarr-exporter"
    static_configs:
      - targets: ["sonarr-exporter:9707"]

  - job_name: "radarr-exporter"
    static_configs:
      - targets: ["radarr-exporter:9708"]

  - job_name: "nzbget-exporter"
    static_configs:
      - targets: ["nzbget-exporter:9710"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "transmission-exporter"
    static_configs:
      - targets: ["transmission-exporter:9116"]

remote_write:
  - url: "${GRAFANA_CLOUD_URL}"
    basic_auth:
      username: "${GRAFANA_CLOUD_USER}"
      password: "${GRAFANA_CLOUD_API_KEY}"

